# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main_frame(object):
    def setupUi(self, main_frame):
        main_frame.setObjectName(_fromUtf8("main_frame"))
        main_frame.resize(1009, 500)
        main_frame.setMinimumSize(QtCore.QSize(900, 500))
        self.mainWidget = QtGui.QWidget(main_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.gridLayout = QtGui.QGridLayout(self.mainWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.mainWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Finger1_widget = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Finger1_widget.sizePolicy().hasHeightForWidth())
        self.Finger1_widget.setSizePolicy(sizePolicy)
        self.Finger1_widget.setAutoFillBackground(False)
        self.Finger1_widget.setStyleSheet(_fromUtf8("border-right: 1px solid gray; \n"""))
        self.Finger1_widget.setObjectName(_fromUtf8("Finger1_widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Finger1_widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Finger1_label = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.Finger1_label.sizePolicy().hasHeightForWidth())
        self.Finger1_label.setSizePolicy(sizePolicy)
        self.Finger1_label.setMinimumSize(QtCore.QSize(0, 30))
        self.Finger1_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(28)
        self.Finger1_label.setFont(font)
        self.Finger1_label.setScaledContents(False)
        self.Finger1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Finger1_label.setObjectName(_fromUtf8("Finger1_label"))
        self.verticalLayout_2.addWidget(self.Finger1_label)
        self.Finger1_formlayout = QtGui.QFormLayout()
        self.Finger1_formlayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.Finger1_formlayout.setObjectName(_fromUtf8("Finger1_formlayout"))
        self.Finger1_motor1_label = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_motor1_label.setObjectName(_fromUtf8("Finger1_motor1_label"))
        self.Finger1_formlayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Finger1_motor1_label)
        self.Finger1_motor1_slider = QtGui.QSlider(self.Finger1_widget)
        self.Finger1_motor1_slider.setMaximum(180)
        self.Finger1_motor1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger1_motor1_slider.setObjectName(_fromUtf8("Finger1_motor1_slider"))
        self.Finger1_formlayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Finger1_motor1_slider)
        self.Finger1_motor2_label = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_motor2_label.setObjectName(_fromUtf8("Finger1_motor2_label"))
        self.Finger1_formlayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Finger1_motor2_label)
        self.Finger1_motor2_slider = QtGui.QSlider(self.Finger1_widget)
        self.Finger1_motor2_slider.setMaximum(180)
        self.Finger1_motor2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger1_motor2_slider.setObjectName(_fromUtf8("Finger1_motor2_slider"))
        self.Finger1_formlayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Finger1_motor2_slider)
        self.Finger1_motor3_label = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_motor3_label.setObjectName(_fromUtf8("Finger1_motor3_label"))
        self.Finger1_formlayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Finger1_motor3_label)
        self.Finger1_motor3_slider = QtGui.QSlider(self.Finger1_widget)
        self.Finger1_motor3_slider.setMaximum(180)
        self.Finger1_motor3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger1_motor3_slider.setObjectName(_fromUtf8("Finger1_motor3_slider"))
        self.Finger1_formlayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Finger1_motor3_slider)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger1_formlayout.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem)
        self.Finger1_motor1_label2 = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_motor1_label2.setObjectName(_fromUtf8("Finger1_motor1_label2"))
        self.Finger1_formlayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.Finger1_motor1_label2)
        self.Finger1_motor1_value = QtGui.QLCDNumber(self.Finger1_widget)
        self.Finger1_motor1_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger1_motor1_value.setObjectName(_fromUtf8("Finger1_motor1_value"))
        self.Finger1_formlayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.Finger1_motor1_value)
        self.Finger1_motor2_label2 = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_motor2_label2.setObjectName(_fromUtf8("Finger1_motor2_label2"))
        self.Finger1_formlayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.Finger1_motor2_label2)
        self.Finger1_motor2_value = QtGui.QLCDNumber(self.Finger1_widget)
        self.Finger1_motor2_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger1_motor2_value.setObjectName(_fromUtf8("Finger1_motor2_value"))
        self.Finger1_formlayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.Finger1_motor2_value)
        self.Finger1_motor3_label2 = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_motor3_label2.setObjectName(_fromUtf8("Finger1_motor3_label2"))
        self.Finger1_formlayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.Finger1_motor3_label2)
        self.Finger1_motor3_value = QtGui.QLCDNumber(self.Finger1_widget)
        self.Finger1_motor3_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger1_motor3_value.setObjectName(_fromUtf8("Finger1_motor3_value"))
        self.Finger1_formlayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.Finger1_motor3_value)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger1_formlayout.setItem(7, QtGui.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger1_formlayout.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.Finger1_slip_label = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_slip_label.setObjectName(_fromUtf8("Finger1_slip_label"))
        self.Finger1_formlayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.Finger1_slip_label)
        self.Finger1_slip_value = QtGui.QLCDNumber(self.Finger1_widget)
        self.Finger1_slip_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger1_slip_value.setObjectName(_fromUtf8("Finger1_slip_value"))
        self.Finger1_formlayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.Finger1_slip_value)
        self.Finger1_pressure_label = QtGui.QLabel(self.Finger1_widget)
        self.Finger1_pressure_label.setObjectName(_fromUtf8("Finger1_pressure_label"))
        self.Finger1_formlayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.Finger1_pressure_label)
        self.Finger1_pressure_value = QtGui.QLCDNumber(self.Finger1_widget)
        self.Finger1_pressure_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger1_pressure_value.setObjectName(_fromUtf8("Finger1_pressure_value"))
        self.Finger1_formlayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.Finger1_pressure_value)

        self.Finger1_calibrate = QtGui.QPushButton(self.Finger1_widget)
        self.Finger1_calibrate.setObjectName(_fromUtf8("pushButton"))
        self.Finger1_formlayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.Finger1_calibrate)


        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger1_formlayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem3)
        self.verticalLayout_2.addLayout(self.Finger1_formlayout)
        self.horizontalLayout_2.addWidget(self.Finger1_widget)
        self.Finger2_widget = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Finger2_widget.sizePolicy().hasHeightForWidth())
        self.Finger2_widget.setSizePolicy(sizePolicy)
        self.Finger2_widget.setAutoFillBackground(False)
        self.Finger2_widget.setStyleSheet(_fromUtf8("border-right: 1px solid gray; \n"""))
        self.Finger2_widget.setObjectName(_fromUtf8("Finger2_widget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.Finger2_widget)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.Finger2_label = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.Finger2_label.sizePolicy().hasHeightForWidth())
        self.Finger2_label.setSizePolicy(sizePolicy)
        self.Finger2_label.setMinimumSize(QtCore.QSize(0, 30))
        self.Finger2_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(28)
        self.Finger2_label.setFont(font)
        self.Finger2_label.setScaledContents(False)
        self.Finger2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Finger2_label.setObjectName(_fromUtf8("Finger2_label"))
        self.verticalLayout_10.addWidget(self.Finger2_label)
        self.Finger2_formlayout = QtGui.QFormLayout()
        self.Finger2_formlayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.Finger2_formlayout.setObjectName(_fromUtf8("Finger2_formlayout"))
        self.Finger2_motor1_label = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_motor1_label.setObjectName(_fromUtf8("Finger2_motor1_label"))
        self.Finger2_formlayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Finger2_motor1_label)
        self.Finger2_motor1_slider = QtGui.QSlider(self.Finger2_widget)
        self.Finger2_motor1_slider.setMaximum(180)
        self.Finger2_motor1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger2_motor1_slider.setObjectName(_fromUtf8("Finger2_motor1_slider"))
        self.Finger2_formlayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Finger2_motor1_slider)
        self.Finger2_motor2_label = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_motor2_label.setObjectName(_fromUtf8("Finger2_motor2_label"))
        self.Finger2_formlayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Finger2_motor2_label)
        self.Finger2_motor2_slider = QtGui.QSlider(self.Finger2_widget)
        self.Finger2_motor2_slider.setMaximum(180)
        self.Finger2_motor2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger2_motor2_slider.setObjectName(_fromUtf8("Finger2_motor2_slider"))
        self.Finger2_formlayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Finger2_motor2_slider)
        self.Finger2_motor3_label = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_motor3_label.setObjectName(_fromUtf8("Finger2_motor3_label"))
        self.Finger2_formlayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Finger2_motor3_label)
        self.Finger2_motor3_slider = QtGui.QSlider(self.Finger2_widget)
        self.Finger2_motor3_slider.setMaximum(180)
        self.Finger2_motor3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger2_motor3_slider.setObjectName(_fromUtf8("Finger2_motor3_slider"))
        self.Finger2_formlayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Finger2_motor3_slider)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger2_formlayout.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger2_formlayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem5)
        self.Finger2_motor1_label2 = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_motor1_label2.setObjectName(_fromUtf8("Finger2_motor1_label2"))
        self.Finger2_formlayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.Finger2_motor1_label2)
        self.Finger2_motor1_value = QtGui.QLCDNumber(self.Finger2_widget)
        self.Finger2_motor1_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger2_motor1_value.setObjectName(_fromUtf8("Finger2_motor1_value"))
        self.Finger2_formlayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.Finger2_motor1_value)
        self.Finger2_motor2_label2 = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_motor2_label2.setObjectName(_fromUtf8("Finger2_motor2_label2"))
        self.Finger2_formlayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.Finger2_motor2_label2)
        self.Finger2_motor2_value = QtGui.QLCDNumber(self.Finger2_widget)
        self.Finger2_motor2_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger2_motor2_value.setObjectName(_fromUtf8("Finger2_motor2_value"))
        self.Finger2_formlayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.Finger2_motor2_value)
        self.Finger2_motor3_label2 = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_motor3_label2.setObjectName(_fromUtf8("Finger2_motor3_label2"))
        self.Finger2_formlayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.Finger2_motor3_label2)
        self.Finger2_motor3_value = QtGui.QLCDNumber(self.Finger2_widget)
        self.Finger2_motor3_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger2_motor3_value.setObjectName(_fromUtf8("Finger2_motor3_value"))
        self.Finger2_formlayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.Finger2_motor3_value)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger2_formlayout.setItem(7, QtGui.QFormLayout.LabelRole, spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger2_formlayout.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem7)
        self.Finger2_slip_label = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_slip_label.setObjectName(_fromUtf8("Finger2_slip_label"))
        self.Finger2_formlayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.Finger2_slip_label)
        self.Finger2_pressure_label = QtGui.QLabel(self.Finger2_widget)
        self.Finger2_pressure_label.setObjectName(_fromUtf8("Finger2_pressure_label"))
        self.Finger2_formlayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.Finger2_pressure_label)
        self.Finger2_slip_value = QtGui.QLCDNumber(self.Finger2_widget)
        self.Finger2_slip_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger2_slip_value.setObjectName(_fromUtf8("Finger2_slip_value"))
        self.Finger2_formlayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.Finger2_slip_value)
        self.Finger2_pressure_value = QtGui.QLCDNumber(self.Finger2_widget)
        self.Finger2_pressure_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger2_pressure_value.setObjectName(_fromUtf8("Finger2_pressure_value"))

        self.Finger2_calibrate = QtGui.QPushButton(self.Finger2_widget)
        self.Finger2_calibrate.setObjectName(_fromUtf8("pushButton"))
        self.Finger2_formlayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.Finger2_calibrate)

        self.Finger2_formlayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.Finger2_pressure_value)
        self.verticalLayout_10.addLayout(self.Finger2_formlayout)
        self.horizontalLayout_2.addWidget(self.Finger2_widget)
        self.Finger3_widget = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Finger3_widget.sizePolicy().hasHeightForWidth())
        self.Finger3_widget.setSizePolicy(sizePolicy)
        self.Finger3_widget.setAutoFillBackground(False)
        self.Finger3_widget.setStyleSheet(_fromUtf8("border-right: 1px solid gray; \n"""))
        self.Finger3_widget.setObjectName(_fromUtf8("Finger3_widget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.Finger3_widget)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.Finger3_label = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.Finger3_label.sizePolicy().hasHeightForWidth())
        self.Finger3_label.setSizePolicy(sizePolicy)
        self.Finger3_label.setMinimumSize(QtCore.QSize(0, 30))
        self.Finger3_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(28)
        self.Finger3_label.setFont(font)
        self.Finger3_label.setScaledContents(False)
        self.Finger3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Finger3_label.setObjectName(_fromUtf8("Finger3_label"))
        self.verticalLayout_11.addWidget(self.Finger3_label)
        self.Finger3_formlayout = QtGui.QFormLayout()
        self.Finger3_formlayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.Finger3_formlayout.setObjectName(_fromUtf8("Finger3_formlayout"))
        self.Finger3_motor1_label = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_motor1_label.setObjectName(_fromUtf8("Finger3_motor1_label"))
        self.Finger3_formlayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Finger3_motor1_label)
        self.Finger3_motor1_slider = QtGui.QSlider(self.Finger3_widget)
        self.Finger3_motor1_slider.setMaximum(180)
        self.Finger3_motor1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger3_motor1_slider.setObjectName(_fromUtf8("Finger3_motor1_slider"))
        self.Finger3_formlayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Finger3_motor1_slider)
        self.Finger3_motor2_label = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_motor2_label.setObjectName(_fromUtf8("Finger3_motor2_label"))
        self.Finger3_formlayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Finger3_motor2_label)
        self.Finger3_motor2_slider = QtGui.QSlider(self.Finger3_widget)
        self.Finger3_motor2_slider.setMaximum(180)
        self.Finger3_motor2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger3_motor2_slider.setObjectName(_fromUtf8("Finger3_motor2_slider"))
        self.Finger3_formlayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Finger3_motor2_slider)
        self.Finger3_motor3_label = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_motor3_label.setObjectName(_fromUtf8("Finger3_motor3_label"))
        self.Finger3_formlayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Finger3_motor3_label)
        self.Finger3_motor3_slider = QtGui.QSlider(self.Finger3_widget)
        self.Finger3_motor3_slider.setMaximum(180)
        self.Finger3_motor3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Finger3_motor3_slider.setObjectName(_fromUtf8("Finger3_motor3_slider"))
        self.Finger3_formlayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Finger3_motor3_slider)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger3_formlayout.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem8)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger3_formlayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem9)
        self.Finger3_motor1_label2 = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_motor1_label2.setObjectName(_fromUtf8("Finger3_motor1_label2"))
        self.Finger3_formlayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.Finger3_motor1_label2)
        self.Finger3_motor1_value = QtGui.QLCDNumber(self.Finger3_widget)
        self.Finger3_motor1_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger3_motor1_value.setObjectName(_fromUtf8("Finger3_motor1_value"))
        self.Finger3_formlayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.Finger3_motor1_value)
        self.Finger3_motor2_label2 = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_motor2_label2.setObjectName(_fromUtf8("Finger3_motor2_label2"))
        self.Finger3_formlayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.Finger3_motor2_label2)
        self.Finger3_motor2_value = QtGui.QLCDNumber(self.Finger3_widget)
        self.Finger3_motor2_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger3_motor2_value.setObjectName(_fromUtf8("Finger3_motor2_value"))
        self.Finger3_formlayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.Finger3_motor2_value)
        self.Finger3_motor3_label2 = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_motor3_label2.setObjectName(_fromUtf8("Finger3_motor3_label2"))
        self.Finger3_formlayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.Finger3_motor3_label2)
        self.Finger3_motor3_value = QtGui.QLCDNumber(self.Finger3_widget)
        self.Finger3_motor3_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger3_motor3_value.setObjectName(_fromUtf8("Finger3_motor3_value"))
        self.Finger3_formlayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.Finger3_motor3_value)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger3_formlayout.setItem(7, QtGui.QFormLayout.LabelRole, spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Finger3_formlayout.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem11)
        self.Finger3_slip_label = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_slip_label.setObjectName(_fromUtf8("Finger3_slip_label"))
        self.Finger3_formlayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.Finger3_slip_label)
        self.Finger3_pressure_label = QtGui.QLabel(self.Finger3_widget)
        self.Finger3_pressure_label.setObjectName(_fromUtf8("Finger3_pressure_label"))
        self.Finger3_formlayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.Finger3_pressure_label)
        self.Finger3_slip_value = QtGui.QLCDNumber(self.Finger3_widget)
        self.Finger3_slip_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger3_slip_value.setObjectName(_fromUtf8("Finger3_slip_value"))
        self.Finger3_formlayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.Finger3_slip_value)
        self.Finger3_pressure_value = QtGui.QLCDNumber(self.Finger3_widget)
        self.Finger3_pressure_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Finger3_pressure_value.setObjectName(_fromUtf8("Finger3_pressure_value"))
        self.Finger3_formlayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.Finger3_pressure_value)

        self.Finger3_calibrate = QtGui.QPushButton(self.Finger3_widget)
        self.Finger3_calibrate.setObjectName(_fromUtf8("pushButton"))
        self.Finger3_formlayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.Finger3_calibrate)

        self.verticalLayout_11.addLayout(self.Finger3_formlayout)
        self.horizontalLayout_2.addWidget(self.Finger3_widget)
        self.Hand_widget = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Hand_widget.sizePolicy().hasHeightForWidth())
        self.Hand_widget.setSizePolicy(sizePolicy)
        self.Hand_widget.setAutoFillBackground(False)
        self.Hand_widget.setStyleSheet(_fromUtf8("border-right: 1px solid gray; \n"""))
        self.Hand_widget.setObjectName(_fromUtf8("Hand_widget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.Hand_widget)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setSpacing(20)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.Finger3_label_2 = QtGui.QLabel(self.Hand_widget)
        self.Finger3_label_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.Finger3_label_2.sizePolicy().hasHeightForWidth())
        self.Finger3_label_2.setSizePolicy(sizePolicy)
        self.Finger3_label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.Finger3_label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(28)
        self.Finger3_label_2.setFont(font)
        self.Finger3_label_2.setScaledContents(False)
        self.Finger3_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Finger3_label_2.setObjectName(_fromUtf8("Finger3_label_2"))
        self.verticalLayout_12.addWidget(self.Finger3_label_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.pushButton = QtGui.QPushButton(self.Hand_widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.Hand_widget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.Hand_widget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.pushButton_3)
        self.verticalLayout_12.addLayout(self.formLayout)
        self.horizontalLayout_2.addWidget(self.Hand_widget)
        self.horizontalLayout.addWidget(self.widget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        main_frame.setCentralWidget(self.mainWidget)

        self.retranslateUi(main_frame)
        QtCore.QMetaObject.connectSlotsByName(main_frame)

    def retranslateUi(self, main_frame):
        main_frame.setWindowTitle(_translate("main_frame", "Gripper hand", None))
        self.Finger1_label.setText(_translate("main_frame", "Finger 1", None))
        self.Finger1_motor1_label.setText(_translate("main_frame", "Motor 1", None))
        self.Finger1_motor2_label.setText(_translate("main_frame", "Motor 2", None))
        self.Finger1_motor3_label.setText(_translate("main_frame", "Motor 3", None))
        self.Finger1_motor1_label2.setText(_translate("main_frame", "Motor 1", None))
        self.Finger1_motor2_label2.setText(_translate("main_frame", "Motor 2", None))
        self.Finger1_motor3_label2.setText(_translate("main_frame", "Motor 3", None))
        self.Finger1_slip_label.setText(_translate("main_frame", "Slip", None))
        self.Finger1_pressure_label.setText(_translate("main_frame", "Pressure", None))
        self.Finger2_label.setText(_translate("main_frame", "Finger 2", None))
        self.Finger2_motor1_label.setText(_translate("main_frame", "Motor 1", None))
        self.Finger2_motor2_label.setText(_translate("main_frame", "Motor 2", None))
        self.Finger2_motor3_label.setText(_translate("main_frame", "Motor 3", None))
        self.Finger2_motor1_label2.setText(_translate("main_frame", "Motor 1", None))
        self.Finger2_motor2_label2.setText(_translate("main_frame", "Motor 2", None))
        self.Finger2_motor3_label2.setText(_translate("main_frame", "Motor 3", None))
        self.Finger2_slip_label.setText(_translate("main_frame", "Slip", None))
        self.Finger2_pressure_label.setText(_translate("main_frame", "Pressure", None))
        self.Finger3_label.setText(_translate("main_frame", "Finger 3", None))
        self.Finger3_motor1_label.setText(_translate("main_frame", "Motor 1", None))
        self.Finger3_motor2_label.setText(_translate("main_frame", "Motor 2", None))
        self.Finger3_motor3_label.setText(_translate("main_frame", "Motor 3", None))
        self.Finger3_motor1_label2.setText(_translate("main_frame", "Motor 1", None))
        self.Finger3_motor2_label2.setText(_translate("main_frame", "Motor 2", None))
        self.Finger3_motor3_label2.setText(_translate("main_frame", "Motor 3", None))
        self.Finger3_slip_label.setText(_translate("main_frame", "Slip", None))
        self.Finger3_pressure_label.setText(_translate("main_frame", "Pressure", None))
        self.Finger3_label_2.setText(_translate("main_frame", "Hand", None))
        self.pushButton.setText(_translate("main_frame", "Open hand", None))
        self.pushButton_2.setText(_translate("main_frame", "Close hand", None))
        self.pushButton_3.setText(_translate("main_frame", "Idle hand", None))

        self.Finger1_calibrate.setText(_translate("main_frame", "Calibrate", None))
        self.Finger2_calibrate.setText(_translate("main_frame", "Calibrate", None))
        self.Finger3_calibrate.setText(_translate("main_frame", "Calibrate", None))


    def set_finger1_motor1_value(self, value):
        print("value: ", value)
        self.Finger1_motor1_value.display(value)

    def set_finger1_motor2_value(self, value):
        self.Finger1_motor2_value.display(value)

    def set_finger1_motor3_value(self, value):
        self.Finger1_motor3_value.display(value)

    def set_finger2_motor1_value(self, value):
        self.Finger2_motor1_value.display(value)

    def set_finger2_motor2_value(self, value):
        self.Finger2_motor2_value.display(value)

    def set_finger2_motor3_value(self, value):
        self.Finger2_motor3_value.display(value)

    def set_finger3_motor1_value(self, value):
        self.Finger3_motor1_value.display(value)

    def set_finger3_motor2_value(self, value):
        self.Finger3_motor2_value.display(value)

    def set_finger3_motor3_value(self, value):
        self.Finger3_motor3_value.display(value)

